### ISSUE TITLE
Improve naming of getImmediateDependencies function

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator-model-sdk#122]
#### Reason/Context
We need to find a replacement name for this function since it is not clear what it does.

https://github.com/asyncapi/generator-model-sdk/blob/0a8f5e3093620a4ff064361c896fc6955ad136e0/src/models/CommonModel.ts#L186

#### Description
What it means is any direct/immediate/nearest dependencies of models. An example could `modelA` have the property `prop1` that refers to another model - `modelB`. The immediate dependencies for `modelA` is then `modelB` because it is referenced through `prop1`. If `modelB` had any dependencies on its own, `modelA` would not return those since it is not the immediate dependencies.

@magicmatatjahu suggested `getNearestDependencies` as a replacement which I agree could be a good solution, any other suggestions?

**Comment by aayushmau5** [comment]
Looking at the comment
```
/**
   * This function returns an array of `$id`s from all the CommonModel's it immediate depends on.
   */
  ```
  What does "immediate depends" means? I'm trying to understand what it does so I can suggest a good name.

**Comment by jonaslagoni** [comment]
hey, @aayushmau5 sorry for the late response must have slipped through the notifications. I have updated the issue with a better description of what the function does.

**Comment by aayushmau5** [comment]
Oops, forgot about this. Sorry. Looking at the explanation, the only alternative I can think of is `getDirectDependencies` but I like `getNearestDependencies` more.

**Comment by jonaslagoni** [comment]
Okay let's go with `getNearestDependencies`, it is definitely better than what we have now.
