### ISSUE TITLE
mergeCommonModels function doesn`t merge required field

### ISSUE THREAD

**Issue by czlowiek488** [asyncapi/generator-model-sdk#158]
#### Describe the bug
mergeCommonModels doesn`t merge required field

#### How to Reproduce
use allOf with objects with required properties

#### Expected behavior
mergeCommonModels does merge required fields

**Comment by czlowiek488** [comment]
add
```
        if(mergeFrom.required instanceof Array) {
            mergeTo.required = [...(mergeTo.required || []), ...mergeFrom.required];
        }
```
to line 154 in CommonModel

**Comment by jonaslagoni** [comment]
Good catch @czlowiek488! Do you want to add a PR fixing this? 🙂

**Comment by czlowiek488** [comment]
Sorry, I don`t have time now and in nearest future. I must finish my generator ASAP.

**Comment by jonaslagoni** [comment]
@czlowiek488 I provided a fix for this bug, feel free to review it if you have the time of course!

**Comment by jonaslagoni** [comment]
@all-contributors please add @czlowiek488 for bug
