### ISSUE TITLE
Use proper string parsing

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator-model-sdk#196]
#### Reason/Context
We have a security eslint rule for `Generic Object Injection Sink`, that forces us to cast a variable to string when used as a key. At the moment we in many places use string injections such as `${variable}` where we should use `String(variable)`.

Based on the following discussion: https://github.com/asyncapi/generator-model-sdk/pull/184#discussion_r632278908

#### Description
Example location that should change: https://github.com/asyncapi/generator-model-sdk/blob/10250e8338ddbcf8222f68e0bed0c6512c863a99/src/models/CommonModel.ts#L194

**Comment by arjungarg07** [comment]
@jonaslagoni can I take up this issue?

**Comment by jonaslagoni** [comment]
@arjungarg07 of course!
