### ISSUE TITLE
Document how to use the sdk

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/generator-model-sdk#46]
We should document how user/dev should use our `model-sdk` in templates - here we should have examples with React and Nunjucks templating - in library, or in normal app.

Documents should contain also complex cases like:
- how to use pass options to generators.
- how to use presets in given language - with overriding case, concatenation etc.

Also we should update main Readme.md to provide information what user/dev should do to use out package and small introduction to package like in react-sdk package.

**Comment by jonaslagoni** [comment]
@magicmatatjahu this can be closed right? 🤔

**Comment by magicmatatjahu** [comment]
@jonaslagoni No, we haven't this part:

> Documents should contain also complex cases like:
>
> how to use pass options to generators.
> how to use presets in given language - with overriding case, concatenation etc.

**Comment by jonaslagoni** [comment]
Ahh! gotcha.
