### ISSUE TITLE
Npm dependencies security report

### ISSUE THREAD

**Issue by siathalysedI** [asyncapi/generator-model-sdk#463]
#### Describe the bug
Hi all, 

I installed the dependencies and I got this message

````
up to date, audited 1421 packages in 16s

90 packages are looking for funding
  run `npm fund` for details

34 vulnerabilities (7 moderate, 27 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
````

My versions are:

````
npm: 7.24.0
node: v16.10.0
````

Full log here:
https://gist.github.com/intfrr/29a6289378e724a5f71359300a0b7103

So please let me know if any comments on how to solve this so it don't show me this warnings

**Comment by derberg** [comment]
oh, interesting, thanks for pointing out. I quickly checked and we do not have `Dependabot alerts` activated on the repo. Dependabot should handle updating of vulnerable dependencies once they release fixes. @jonaslagoni do you know why it is not enabled, is it because of active development?

**Comment by jonaslagoni** [comment]
Great question, I have no idea 😄 Honestly thought it was 🤷 

All Dependabot features enabled. 

Gonna go through all dependencies and update them.
