### ISSUE TITLE
Enum in TS for const types

### ISSUE THREAD

**Issue by panwauu** [asyncapi/generator-model-sdk#464]
#### Describe the bug
For a constant property a new enum is created with only this one key. Now I cannot simply assign the constant value but rather I have to use the enum and the key in the enum. This is problematic as I cannot predict the enum name beforehand (sometimes it is AnonymousSchema_X). It would be easier to use if the const is translated to a constant typescript type.

For example I have a constant property event with only possible key 'ping'. This generated code, desired generated code and my desired usage of the code is displayed below:
```
Generated:
export interface Root {
    event: Event;
}
export enum Event {
    PING = "ping",
}

Desired:
export interface Root {
    event: "ping";
}

Usage:
let test: Root = {
    event: "ping"
}
```

#### How to Reproduce
Use this jsonSchema in the typescript-interface example
```
const jsonSchemaDraft7 = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  additionalProperties: false,
  "properties": {
    "event": {
      "type": "string",
      "const": "ping"
    }
  },
  "required": [
    "event"
  ]
};
```

**Comment by jonaslagoni** [comment]
Thanks for the issue @panwauu, I definitely see the use case.

How about if the enum contains multiple enums, what would your desired output be?

```json
{
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  additionalProperties: false,
  "properties": {
    "event": {
      "type": "string",
      "enum": ["ping", "pong"]
    }
  },
  "required": [
    "event"
  ]
}
```

**Comment by jonaslagoni** [comment]
It is definitely possible, and we actually already have it [supported in the TS renderer](https://github.com/asyncapi/modelina/blob/1e71b3b2cab6bc2c277001fcafe7e1b8ed175ce9/src/generators/typescript/TypeScriptRenderer.ts#L56).

The "problem" is by [default enums are separated into their own model](https://github.com/asyncapi/modelina/blob/1e71b3b2cab6bc2c277001fcafe7e1b8ed175ce9/src/interpreter/PostInterpreter.ts#L24), properties will never have properties with enums (as they are rendered on their own). 

I think it would be great to have more fine-tuned control here, so you as a user can define the behavior of the interpretation.

Only thing is, this is highly dependent on the language generators, and what they support. i.e. for Java, this configuration makes no sense, as it is simply not possible 😄 

Do you want to try and contribute to this change? I can guide you through it in any detail you'd like 🙂

**Comment by panwauu** [comment]
I thought about and think that enumType is fine. Hope you find everything in order with this PR
