### ISSUE TITLE
Remove Eslint warnings

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/generator-model-sdk#53]
#### Reason/Context
Currently we ignore warnings but it needs to be addressed. Especially the complexity check. After that we need to force no warnings.

**Comment by magicmatatjahu** [comment]
Partially done in https://github.com/asyncapi/generator-model-sdk/pull/60

**Comment by jonaslagoni** [comment]
Completely done in https://github.com/asyncapi/generator-model-sdk/pull/81
