### ISSUE TITLE
Fix simplification of tuple 

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/generator-model-sdk#67]
#### Describe the bug

When I fixing rendering the tuple for TS, I found the bug.

At the moment given schema:

```json
{ "type": "array", "items": [{ "type": "string" }, { "type": "number" }] }
```

produces given CommonModel:

```ts
CommonModel {
  originalSchema: Schema { type: 'array', items: [ [Schema], [Schema] ] },
  type: [ 'string', 'number' ]
}
```

and this is not true, because it's a tuple, not an array of unions. We should fix it.

**Comment by magicmatatjahu** [comment]
Also if I write something like:

```json
{ "type": "array", "items": { "oneOf": [ { "type": "string" }, { "type": "number" } ] } }
```

then this is true union, but I give this same CommonModel, like in tuple case, so user/dev cannot determine which type should be rendered for model ans must for that check the originalSchema, which is not acceptable.

**Comment by jonaslagoni** [comment]
This might get fixed by an upcoming pr, there are a bug in the type simplifier.

**Comment by jonaslagoni** [comment]
The simplifier does semi-require the root schema to be an object... I'll try spend a few hours to figure out how we can handle this better.

**Comment by jonaslagoni** [comment]
Current implementation (with all the PR's merged) the CommonModel would look like 
```
{
  originalSchema: {
    type: "array",
    items: [
      {
        type: "string",
      },
      {
        type: "number",
      },
    ],
  },
  type: "array",
  items: {
    type: [
      "string",
      "number",
    ],
    originalSchema: {
      type: "array",
      items: [
        {
          type: "string",
        },
        {
          type: "number",
        },
      ],
    },
  },
}
```
Which is as expected right?

**Comment by magicmatatjahu** [comment]
@jonaslagoni No, this is not a true, because this schema indicates that you have an array of union, not a tuple. We should have schema like this:

```ts
"items": [
  { type: "string" },
  { type: "number" },
]
```

**Comment by magicmatatjahu** [comment]
We conclude that this a feature request, but also a bug :)
