### ISSUE TITLE
Add support for JSON Schema files as input

### ISSUE THREAD

**Issue by smoya** [asyncapi/generator-model-sdk#97]
#### Reason/Context
Considering that we are potentially gonna have parsers written in other languages (not just JS. E.g. https://github.com/asyncapi/parser-go), It makes sense to support an input type that can be used to load schemas generated by any of those.

This will allow using any convenient parser, no matters the language they are implemented on.

This feature request was motivated by this [PR review comment](https://github.com/asyncapi/generator-model-sdk/pull/87#discussion_r580941224).

#### Description
Ideally, the parsers should be able to generate JSON Schema files so they can be used later by this generator.

**Comment by jonaslagoni** [comment]
I think we can expand this to support AsyncAPI file inputs as well.

Just to clarify what you mean by supporting other parser input. Do you mean you want to use the go parser, then save that output to a file, for then to generate models based on that parsed filed? 🤔

**Comment by smoya** [comment]
> I think we can expand this to support AsyncAPI file inputs as well.

Would that become a new independent Issue?

> Just to clarify what you mean by supporting other parser input. Do you mean you want to use the go parser, then save that output to a file, for then to generate models based on that parsed filed? 🤔

Yes. Does it make sense? A bit new to the game so feel free to say it doesn't.

**Comment by jonaslagoni** [comment]
> Yes. Does it make sense? A bit new to the game so feel free to say it doesn't.

I simply don't see a use-case 😄 In what use-case do you see people wanting to use the GO parser for then to save the output of that to a file for then to use this library? Wouldnt you just want to provide an AsyncAPI file directly to this library? IMO you don't need to know the underlying parser 🤔

**Comment by smoya** [comment]
> > Yes. Does it make sense? A bit new to the game so feel free to say it doesn't.
> 
> I simply don't see a use-case 😄 In what use-case do you see people wanting to use the GO parser for then to save the output of that to a file for then to use this library? Wouldnt you just want to provide an AsyncAPI file directly to this library? IMO you don't need to know the underlying parser 🤔

Yeah, you made me think on it a bit deeply and indeed it makes more sense to just use the AsyncAPI file directly as it is the source of truth.
I'm gonna close this and create a new issue for that so we have a cleaner start.
